import { Empty, Notice, PageHeader, Status } from '../../components/chrome';
import { date, money, percent } from '../../lib/format';
import { createEngagement } from '../../server/actions';
import { queries, tenantId } from '../../server/runtime';

export const dynamic = 'force-dynamic';
export default async function Commerce({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const [summary, message] = await Promise.all([queries().commerce(tenantId()), searchParams]);
  return <><PageHeader eyebrow="Commerce" title="The value behind the work." description="Contracted revenue, modeled delivery costs, planned creator payouts, and contribution margin in integer minor units." />
    <Notice error={message.error} success={message.success} />
    <section className="metric-grid">{[['Contracted revenue', money(summary.totals.revenue), 'portfolio total'], ['Modeled costs', money(summary.totals.costs), 'costs + payouts'], ['Contribution margin', money(summary.totals.contributionMargin), percent(summary.totals.marginRatio)]].map(([name, value, note]) => <div className="metric" key={name}><small>{name}</small><strong>{value}</strong><em>{note}</em></div>)}</section>
    <div className="split"><section><h2>Engagements</h2>{summary.engagements.length === 0 ? <Empty title="No commercial engagements">Attach a project or retainer to one or more campaigns.</Empty> : <div style={{ display: 'grid', gap: 16 }}>{summary.engagements.map(({ engagement, economics, campaignNames }) => <article className="panel" key={engagement.id}><div className="panel-head"><div><Status value={engagement.kind} /><h2 style={{ marginTop: 10 }}>{engagement.package.name}</h2></div><strong>{money(economics.revenue)}</strong></div><p>{campaignNames.join(' · ')}</p><div className="economics"><div><small>Delivery cost</small><strong>{money(economics.costs)}</strong></div><div><small>Contribution</small><strong>{money(economics.contributionMargin)}</strong></div><div><small>Margin</small><strong>{percent(economics.marginRatio)}</strong></div></div><dl className="definition" style={{ marginTop: 22 }}><dt>Direct costs</dt><dd>{engagement.costs.length === 0 ? 'None' : engagement.costs.map((cost) => `${cost.description}: ${money(cost.amount)}`).join(' · ')}</dd><dt>Creator payouts</dt><dd>{engagement.creatorPayouts.length === 0 ? 'None' : engagement.creatorPayouts.map((payout) => `${payout.creatorId}: ${money(payout.amount)} (${payout.status})`).join(' · ')}</dd></dl><div className="card-meta"><span>{date(engagement.startsAt)}{engagement.endsAt ? `—${date(engagement.endsAt)}` : ''}</span><span>{engagement.package.deliverables.join(' · ')}</span></div></article>)}</div>}</section>
      <aside className="form-panel"><h2>Create engagement</h2>{summary.campaigns.length === 0 ? <p>Create a campaign before modeling an engagement.</p> : <form action={createEngagement}><fieldset style={{ border: 0, padding: 0 }}><legend className="eyebrow">Campaigns</legend>{summary.campaigns.map(({ campaign, brandName }) => <label key={campaign.id} style={{ gridTemplateColumns: '20px 1fr', alignItems: 'start', marginTop: 8 }}><input type="checkbox" name="campaignIds" value={campaign.id} style={{ width: 16 }} /><span>{campaign.name}<small style={{ display: 'block' }}>{brandName}</small></span></label>)}</fieldset><label>Engagement type<select name="kind"><option value="project">Project</option><option value="retainer">Retainer</option></select></label><div className="form-row"><label>Package code<input name="packageCode" required placeholder="story-sprint" /></label><label>Package name<input name="packageName" required placeholder="Editorial Story Sprint" /></label></div><label>Deliverables<textarea name="deliverables" required placeholder="Strategy, 6 short films, report" /></label><label>Contracted revenue (USD)<input name="revenue" inputMode="decimal" required placeholder="48000.00" /></label><div className="form-row"><label>Production costs<input name="cost" inputMode="decimal" required defaultValue="0.00" /></label><label>Creator payouts<input name="payout" inputMode="decimal" required defaultValue="0.00" /></label></div><div className="form-row"><label>Starts<input name="startsAt" type="datetime-local" required /></label><label>Ends<input name="endsAt" type="datetime-local" /></label></div><button className="button primary">Create engagement</button></form>}</aside></div>
  </>;
}
